# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61976105756151fd858ae3e47e8598574752ca1d29213d276d25d10ea20a8a3245847c6506c8688fe1ee9fef5501298b9a5bd5623a496252391cc8012559d464

test:
  secret_key_base: 92514238d71d7a35be99201d46f94166581a6e25158697e52c79a2a1fca80474538caba3e8e44042069c8b199507a45aca3226022ee500605fc34db01120e70e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
